### ISSUE TITLE
Build for play 2.6 and scala 2.12

### ISSUE THREAD

**Issue by cardamo** [tototoshi/play-json-naming#3]
Hey @tototoshi, thanks for this lib!

[Play 2.6 is coming](https://github.com/playframework/playframework/releases/tag/2.6.0-M2), could you publish a build with scala 2.12?

**Comment by tototoshi** [comment]
published 1.2.0-SNAPSHOT. This is built with Scala 2.12, 2.11 and Play 2.6.0-M2.

**Comment by atduarte** [comment]
@tototoshi where is that published? Thanks.

**Comment by tototoshi** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/tototoshi/play-json-naming_2.11/1.2.0-SNAPSHOT/

**Comment by atduarte** [comment]
play-json-naming_2.11 not play-json-naming_2.12 ?

**Comment by tototoshi** [comment]
@atduarte https://oss.sonatype.org/content/repositories/snapshots/com/github/tototoshi/play-json-naming_2.12/1.2.0-SNAPSHOT/ you want this?
